### ISSUE TITLE
Update operator version to 1.2

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_controller#103]
Update and test the new operator version

**Vibhav Bobade**
@Lidia Mokevnina
```
 in this version you wouldn't have to give the following config to the operator
ingress:
    cluster:
      ingressAnnotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
    syncFromManifests: true
```
