### ISSUE TITLE
Set etcd as the defualt external datastore from the controller while creating the UffizziCluster

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi_controller#115]
like below
```
kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: basic-etcd-x-8
spec:
  ingress:
    host: testns2.uclusters.app.qa-gke.uffizzi.com
  externalDatastore: etcd
```
