### ISSUE TITLE
Memory limits are not updated

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_controller#20]
In docker-compose.uffizzi.com compose file first the web container had memory specification 

```
    deploy:
      resources:
        limits:
          memory: 4000M
```
While the sidekiq container didn't have one. When I updated it in the compose file and triggered a deploy update, the memory limits for the sidekiq container stayed the same.
