### ISSUE TITLE
Improve `NetworkPolicy` for customer Namespaces

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi_controller#25]
Right now we're defining `NetworkPolicy` Resources that block traffic coming into each Namespace from other Namespaces and Pod IP's. We must additional define "egress" rules to block a Pod's connection elsewhere. Right now customer workloads can make TCP connections to the k8s Master API, nodes, and other Namespaces that do not have a `NetworkPolicy` defined.

Customer workload Pods in Deployments specified by this controller should only be able to connect to itself, the load balancer, and The Internet.

**Comment by axisofentropy** [comment]
Our controller currently creates NetworkPolicy Resources for each customer Namespace that look like this.
This permits connections FROM each customer Pod TO all IP addresses EXCEPT for those within the 10.20.x.x range, which is all other Pods. There are exceptions for Pods within our load balancer's namespace (Three load balancer Namespaces are specified because it varies when installed by Terraform, Helm, or legacy.)

Outgoing "egress" connections are not specified so each Pod may connect to anything it can otherwise reach. This includes the k8s Master API, our controller, our k8s nodes, `kube-system` Pods, etc. Each customer Pod cannot connect to other customer Pods because they are still protected in turn by their own NetworkPolicy.

So in summary: our existing policy protects customer Pods from each other but nothing else.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: uffizzi
  name: app-deployment-2129
  namespace: deployment-2129
spec:
  ingress:
  - from:
    - podSelector: {}
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.20.0.0/14
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: uffizzi-controller
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
  podSelector: {}
  policyTypes:
  - Ingress
```

**Comment by axisofentropy** [comment]
Here's an example new `NetworkPolicy` that I'm going to implement and test:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: uffizzi
  name: app-deployment-2128
  namespace: deployment-2128
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: uffizzi-controller
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```
