### ISSUE TITLE
BUG: Multi-Attach error for volume

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_controller#26]
Floating error after next case:

1. Create preview from cli (Using compose file with volumes) `uffizzi preview create`
2. Wait until preview created
3. Make changes in preview DB (e.g. add new user)
4. Update preview `uffizzi preview update`

**Result:** Preview failed.
Error in the Event Log:
```
Multi-Attach error for volume "pvc-ee60af29-0a88-42c4-94b9-81c5ccc766d1" Volume is already used by pod(s) app-deployment-4758-858df776cc-bfrhp
```

```
services:
  volumes_test_app:
    image: zipofar/uffizzi_test_rails_simple:latest
    volumes:
      - share_db:/db
    deploy:
      resources:
        limits:
          memory: 1000M

volumes:
  share_db:

x-uffizzi-ingress:
  service: volumes_test_app
  port: 3000

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```
