### ISSUE TITLE
Fix host volumes with source `./` and add sync host volumes across containers

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_controller#43]

**Comment by moklidia** [comment]
For testing try adding `./` as a volume.

Need to create an app that would update files and check that they are synced. App in progress.

**Comment by NealArw** [comment]
1. Deployment with volume `./` failed

https://app.qa-gke.uffizzi.com/projects/368/deployments/2429/containers

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/199000636-ac2b214c-eb57-4fd4-a4c3-514b62f27cc5.png">

```
version: '3.7'

services:
  web:
    build:
      context: https://github.com/NealArw/hello-world-1#volume-from-the-root
      dockerfile: /Dockerfile
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./

x-uffizzi:
  ingress:
    service: web
    port: 80

  continuous_preview:
    share_to_github: true
    delete_preview_after: 6h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
```

```
bash-5.0# k get pod -n deployment-2429
W1031 11:42:57.701268      91 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
No resources found in deployment-2429 namespace.
bash-5.0#
```
