### ISSUE TITLE
Add possibility to initialize data for named volume

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_controller#49]
For example we have a compose file:
```
version: "3.8"

x-uffizzi:
  ingress:
    service: nginx
    port: 80

services:
  nginx:
    image: nginx
   volumes:
     - app_public:/app/public

  app:
   image: app
   volumes:
     - app_public:/app/public
  
volumes:
  app_public:
  ```
  
Container app has data in directory `/app/public` and container nginx should be get this data when it start.
As I can see this:
* Start init container
* Pull image which has named volume
* Run container from this image and copy files to pvc volume

Possibly problems:
* We do not know size of image
* We do not know size of files should be copy to volume
