### ISSUE TITLE
Hostnames are not updated after update deployment

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_controller#63]
For example we create deployment without services with _ in names and after that we add these services to compose file and update deployment and it works

```
func initializeDeployment(
...
				Spec: corev1.PodSpec{
					Containers:   []corev1.Container{},
					NodeSelector: getPodSpecNodeSelector(),
					Tolerations:  getPodSpecTolerations(),
					HostAliases: []corev1.HostAlias{
						{
							IP:        global.Settings.DefaultIp,
							Hostnames: buildAllowedHostnames(containerList),
						},
					},
					...
```

**Comment by zipofar** [comment]
### HOW TO TEST: ###
* Creating and updating of deployment should work

Example test:
1. Create deployment with single service like:
```
services:
  nginx:
    image: nginx:latest

x-uffizzi:
  ingress:
    service: nginx
    port: 80
```

Then go to the controller and make `kubectl get deployment -n <your_namespace> -o yaml` and check `hostAliases` it should looks like
```
hostAliases:
        - hostnames:
          - nginx
          ip: 127.0.0.1
```

2. Add second service to previous deployment
```
services:
  nginx:
    image: nginx:latest

  redis:
    image: redis:latest

x-uffizzi:
  ingress:
    service: nginx
    port: 80
```

Then go to the controller and make `kubectl get deployment -n <your_namespace> -o yaml` and check `hostAliases` it should looks like
```
hostAliases:
        - hostnames:
          - nginx
          - redis
          ip: 127.0.0.1
```

**Comment by NealArw** [comment]
**TESTED - OK**

Befor:

```
        hostAliases:
        - hostnames:
          - nginx
          ip: 127.0.0.1
```
After:

```
        hostAliases:
        - hostnames:
          - redis
          - nginx
          ip: 127.0.0.1
```
