### ISSUE TITLE
Do not specify `cert-manager` annotations when `clusterIssuer` is not specified.

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi_controller#7]
We want to use "wildcard" TLS certificates to stop relying upon third-party certificate authorities for each new deployment. This should increase reliability and sometimes speed of new deployments. The easiest way to implement this is to use a single wildcard TLS certificate for all deployments. We think the easiest way to do this with our current implementation is to stop invoking `cert-manager` and instead provide `ingress-nginx` with a "default" wildcard certificate for all preview `Ingresses`.

Our current implementation specifies a `clusterIssuer` as a value for an annotation on each preview `Ingress`:
```
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: zerossl
```

We also specify a `secretName` within the `tls` part of the `Ingress` `spec`:
```
    tls:
    - hosts:
      - deployment-1555.default-adam.app.qa-gke.uffizzi.com
      secretName: deployment-1555.default-adam.app.qa-gke.uffizzi.com
```

Proposed behavior: When the value of the environment variable `CERT_MANAGER_CLUSTER_ISSUER` is empty or not defined, do not add the `cert-manager` annotation and also do not specify a `secretName`. These two changes will prevent `cert-manager` from requesting a certificate and also instruct `ingress-nginx` to use its default certificate, which will be an appropriate wildcard certificate.
