### ISSUE TITLE
Multi-Attach error for volume

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_controller#82]
A user is getting the following error:

Multi-Attach error for volume "pvc-xxxx" Volume is already exclusively attached to one node and can't be attached to another

Compose file:

```
x-uffizzi:
  ingress: # required
    service: nginx
    port: 80
    additional_subdomains:
      - "subdomain"
service:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d/
 ```
